Cooking BookWEB/src/bean/ShoppingListBean.java
/**
* Because this bean correspond to maintain shopping list must be session scope.
*  Otherwise selected recipe will be not access, so list can not be create 
 */
package bean;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

import javax.ejb.EJB;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import dataExport.SendDataBeanRemote;
import dataExport.mail.MailRemote;
import recipes.CookingRecipe;
import recipes.Ingredient;
import servlets.Details;
import shoppingList.ShoppingBeanRemote;


/**
 * this class correspond to maintain user shopping list
 * 
 * @author Dawid
 * @since 14.01.2018
 */
public class ShoppingListBean implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@EJB
	private ShoppingBeanRemote shoppingBean;
	@EJB
	private MailRemote mailBean;
	@EJB
	private SendDataBeanRemote mailDocument;
	private CookingRecipe currentRecipe;
	// send to mail address
	private String mail;

	/**
	 * Set current recipe.Must be called before {@link #addToShoppingList()}
	 * @param currentRecipe
	 *            the currentRecipe to set. 
	 */
	public void setCurrentRecipe(CookingRecipe currentRecipe) {
		this.currentRecipe = currentRecipe;
	}

	/**
	 * 
	 * Call {@link ShoppingBeanRemote#addToList(long, String, java.util.List)}
	 */
	public void addToShoppingList() {
		shoppingBean.addToList(currentRecipe.getId(), currentRecipe.getName(), currentRecipe.getIngredients());
	}

	/**
	 * Return ingredients list that was generated as shopping list
	 * 
	 * @return
	 */
	public List<Ingredient> getIngredients() {
		return shoppingBean.getIngredientsList();
	}

	/**
	 * Return map that key is {@link CookingRecipe} name and value is a id
	 * 
	 * @return
	 */
	public Map<String, Long> getNamesAndId() {
		return shoppingBean.getIdAndName();
	}

	/**
	 * This method get parameter open from request and redirect to {@link Details}.
	 */
	public void openHyperlink() {
		//
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			// set display parameter and call redirect to Details servlet
			context.getExternalContext()
					.redirect("Details?display=" + context.getExternalContext().getRequestParameterMap().get("open"));
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	/**
	 * Send mail to provide address
	 */
	public void sendMail() {
		//// get language properties, set mail subject according to user langugae preferences
		ResourceBundle bundle = FacesContext.getCurrentInstance().getApplication()
				.getResourceBundle(FacesContext.getCurrentInstance(), "mainLang");
		//// This get main path string 
		HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		String url = req.getRequestURL().toString();
		String path =url.substring(0, url.length() - req.getRequestURI().length()) + req.getContextPath();
			//// Create and configure MailBean
		mailBean.configureAddress(mail, new String(bundle.getString("short_title") + " - " + bundle.getString("shopping_list")));
		mailBean.configureList(bundle.getString("shopping_list"), getIngredients());
		mailBean.configureHyperlink(path, "Details","display",bundle.getString("recipes"), getNamesAndId());
		////	call bean send method 	
		mailDocument.send(mailBean);

		mail = null;
	}

	/**
	 * @return the mail
	 */
	public String getMail() {
		return mail;
	}

	/**
	 * @param mail
	 *            the mail to set
	 */
	public void setMail(String mail) {
		this.mail = mail;
	}
	/**
	 * 
	 */
	public void clear() {
		shoppingBean.clearList();
	}

}

Cooking BookWEB/WebContent/add_new.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/html"
      xmlns:iList ="http://java.sun.com/jsf/composite/composites/ingredients_list"> 
      
 <h:outputStylesheet library="css" name="form.css"/>
<body> 
<!-- include the template file -->
<ui:composition template="template/template.xhtml">
<!-- include own css file  -->
  <ui:define name="css">
<h:outputStylesheet library="css" name="form.css"/>
</ui:define>

     <ui:define name="main_content">
     <div>
		<h:form id="new-form1">
		<!-- Name and category selector -->
		<h:panelGrid columns="8">
		<!-- Recipe name field and validation -->
		<h:outputLabel for="form_name" value="#{formLang.name}" />
		<h:inputText id="form_name" value="#{formBean.name}" required="true" 
		requiredMessage="#{formLang.name_required}" validatorMessage="#{formLang.name_lenght}" 
		onchange="submit()" valueChangeListener="#{formBean.nameChanged}">
			<f:validateLength  minimum="6" /> 
		</h:inputText>
		
<!-- 	Category select list	 -->
		<h:outputLabel for="form_category" value="#{formLang.category}" />
		<h:selectOneMenu id="form_category" value="#{formBean.category}" 
			onchange = "submit()" valueChangeListener="#{formBean.categoryChanged}" >
		<f:selectItems value="#{formBean.categoryList}" />
		</h:selectOneMenu>

<!-- 	Save button 	 -->
		<h:commandButton id="submit" action="#{formBean.save}" value="#{formLang.save}"  />
		</h:panelGrid>
		
		<!-- panel for display validation error  -->
		<h:panelGrid columns="2">
		<h:message for="form_name" errorClass="form_error"/>
		<h:message id="submit_messege" for="submit" errorClass="form_error" infoClass="form_info" />
		</h:panelGrid>
		</h:form>
		</div>
		<!-- Image upload -->	
		<dir>
		<h:form id="new-form-image" enctype="multipart/form-data">
		<h:inputFile id="file" value="#{formBean.image}" rendered="true" validator="#{formBean.validateImage}" >		
		</h:inputFile>
		<h:message for="file" errorClass="form_error" infoClass="form_info" />
		<h:commandButton action="#{formBean.convetToBinary()}" value="#{formLang.add_image}" />
		</h:form>
		</dir>
		<div>
		<h:form id="new-form2">		
				  <!-- ingredients list using composite ingredients_list.xhtml -->
				  		<h:outputLabel for="ingredients" value="#{formLang.ingredients}" />
  	<iList:ingredients_list id="ingredients" ingredients="#{formBean.ingredients}"></iList:ingredients_list>		
<br/>
		<!-- add ingredient to list -->
		<h:panelGrid columns="4">
		<h:inputText id="ingredient_name" value="#{formBean.ingredientName}" required="true" requiredMessage="#{formLang.ingredient_name_required}" />
		<h:inputText id="ingredient_value"  value="#{formBean.ingredientValue}" required="true" requiredMessage="#{formLang.ingredient_value_required}" validatorMessage="#{formLang.ingredient_value_range}" >
		<f:validateDoubleRange minimum="0.0" />
		</h:inputText>	
		<h:selectOneMenu id="ingredient_unit" value="#{formBean.ingredientUnit}" >
		<f:selectItems value="#{formBean.unitList}" />
		</h:selectOneMenu>
		<h:commandButton action="#{formBean.addIngredient}" value="#{formLang.add}"/>
		</h:panelGrid>	
		<h:panelGrid columns="2">
		<h:message for="ingredient_name" errorClass="form_error"/>
		<h:message for="ingredient_value" errorClass="form_error"/>
			</h:panelGrid>
		</h:form>
		</div>		
		
				<div>
		<h:form id="new-form-prepare">			
			<!-- Prepare instruction text area -->
		<h:outputLabel for="form_text_area" value="#{formLang.prepare}" /><br />
		<h:message for="form_text_area" errorClass="form_error"/><br />
		<h:inputTextarea id="form_text_area" cols="70" rows="20" value="#{formBean.prepare}" required="true" requiredMessage="#{formLang.prepare_required}" onchange="submit()" valueChangeListener="#{formBean.prepareChanged}" />
		</h:form>
		
	</div>	
    </ui:define>
</ui:composition> 
</body>
</html>

Cooking BookWEB/WebContent/reciple_detail.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://java.sun.com/jstl/core"
      xmlns:iList ="http://java.sun.com/jsf/composite/composites/ingredients_list"
      xmlns:f="http://java.sun.com/jsf/core"> 
<body>

<!-- include the template file -->
<ui:composition template="template/template.xhtml">	
     <ui:define name="main_content">     
          <!-- get recipe instance to local variable  -->
     <h:form prependId="false" >
     <c:set var="recipe" value="#{detailBean.recipe}" /> 
     <!-- Display Name and category -->
    	<h:panelGrid columns="4" cellpadding="10">
     <h:column><h:outputLabel for="detail-name" value="#{formLang.name}" /> <br/><h:outputText id="detail-name" value="#{recipe.name}" /></h:column>
     <h:column><h:outputLabel for="detail-category" value="#{formLang.category}" /> <br/><h:outputText id="detail-category" value="#{recipe.category}" /></h:column>  
	<h:column>    
	<h:commandButton action="#{shoppingListBean.addToShoppingList()}" value="Add to Shoping list" >
	<f:setPropertyActionListener value="#{recipe}" target="#{shoppingListBean.currentRecipe}"></f:setPropertyActionListener>    
          </h:commandButton>       
	</h:column>	
	<h:column><h:commandButton action="#{detailBean.makePDF()}" value="PDF" /></h:column>
     </h:panelGrid>
 <br/>
 <h:graphicImage value="/Details?print=#{recipe.id}" alt="Recipe image" width="400" height="auto" />
  <!-- ingredients list using composite ingredients_list.xhtml -->
  	<iList:ingredients_list ingredients="#{recipe.ingredients}"></iList:ingredients_list>
         <!-- Display prepare instruction  -->
      <h:outputLabel for="detail-prepare" value="#{formLang.prepare}" />  <br/> 
    <h:inputTextarea id="detail-prepare" value="#{recipe.prepare}" cols="60" rows="20" readonly = "true"/>  
              </h:form>    
  </ui:define>
</ui:composition> 
</body>
</html>

Cooking BookWEB/WebContent/reciple_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"> 
<body>
<!-- include the template file -->
<ui:composition template="template/template.xhtml">
	<!--  serach unsing  -->
	<!-- include own css file  -->
  <ui:define name="css">
<h:outputStylesheet library="css" name="search.css"/>
</ui:define>
	
     <ui:define name="main_content">
	<div class="search">
	<h:form id="search-form">
	<h:outputLabel for="search-field" value="Search" />
	<h:inputText id="search-field" value="#{listBean.searchField}" />
	<h:commandButton action="#{listBean.searchTitle()}" value="Search" />
	</h:form>
	</div>
	<div class="search">
	<h:form id="ingredients-search-form">
	<h:panelGrid columns="2">
	<h:column>
	<h:outputLabel for="ingredients-search-field1" value="Search" /><br />
	<h:inputText id="ingredients-search-field1" value="#{listBean.ingredient1}" /><br />
	<h:inputText id="ingredients-search-field2" value="#{listBean.ingredient2}" /><br />
	<h:inputText id="ingredients-search-field3" value="#{listBean.ingredient3}" /><br />
	<h:inputText id="ingredients-search-field4" value="#{listBean.ingredient4}" /><br />
	<h:inputText id="ingredients-search-field5" value="#{listBean.ingredient5}" /><br />
	</h:column>
	<h:commandButton action="#{listBean.searchIngredients()}" value="Search" />
	</h:panelGrid>
	</h:form>
	</div>
	<div class="list">
			<!-- ingredients list -->
			<h:form prependId="false">
		<h:dataTable value="#{listBean.cookingRecipes}" var="recipe" styleClass="recipe-list">
		<h:column>
		<!-- Call servlet to deliver image -->
		<h:graphicImage value="/Details?print=#{recipe.id}" alt="Recipe image" width="200" height="auto" />
		</h:column>
    <h:column>
        <h:commandLink type="submit" action="reciple_detail" value="#{recipe.name}" >
        <!-- action listener call bean method when click above link -->
        <f:setPropertyActionListener value="#{recipe.id}" target="#{detailBean.recipeId}"/>
        </h:commandLink>
            </h:column>
             <h:column>
        <h:outputLabel value="#{recipe.category}" />
            </h:column>	            
</h:dataTable>
</h:form>
	</div>	
  </ui:define>
</ui:composition> 
</body>
</html>

Cooking BookWEB/WebContent/shopping_list.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:h="http://xmlns.jcp.org/jsf/html"
xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:iList ="http://java.sun.com/jsf/composite/composites/ingredients_list"
      xmlns:c="http://java.sun.com/jsp/jstl/core">  
<body>
<!-- include the template file -->
<ui:composition template="template/template.xhtml">

     <ui:define name="main_content">
<h:form prependId="false">
<h:panelGrid columns="4" cellpadding="5">
<h:column><h:outputLabel value="e-mail" /></h:column>
<h:column>
<h:inputText id="e-mail" value="#{shoppingListBean.mail}" required="true" validatorMessage="e-mail is not valid" requiredMessage="e-mail is not valid">
<f:validateRegex pattern="[\w\.-]*[a-zA-Z0-9_]@[\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]" />
</h:inputText>
</h:column>
<h:column><h:commandButton action="#{shoppingListBean.sendMail()}" value="Send mail" /></h:column>
<h:column><h:commandButton action="#{shoppingListBean.clear()}" value="Remove" immediate="true"/></h:column>
</h:panelGrid>
<h:message for="e-mail" style="color:red"/><br/>
<h:outputLabel value="#{mainLang.shopping_list}" />
  <!-- ingredients list using composite ingredients_list.xhtml -->
  	<iList:ingredients_list ingredients="#{shoppingListBean.ingredients}"></iList:ingredients_list>
  	<h:outputLabel value="#{mainLang.recipes}" />
	<h:panelGrid>
	<c:forEach items="#{shoppingListBean.namesAndId}" var="list">
		<h:column>
		<h:commandLink action="#{shoppingListBean.openHyperlink()}" value="#{list.key}" immediate="true" >
		<f:param name="open" value="#{list.value}"></f:param>
		</h:commandLink>
		</h:column>
	</c:forEach>
	</h:panelGrid>
	</h:form>
  </ui:define>
</ui:composition> 
</body>
</html>